 [[redirects]]
  from = "/proof/YOUVISIT_INSTID/*"
  to = ":splat"
  status = 200

## [[redirects]] 
##  from = "/proof/YOUVISIT_INSTID_TEST/*"
##  to = ":splat"


##[[redirects]]
##  from = "/proof/121419/*"
##  to = ":splat"